title: Tapestry of flimsy steps
author: Marc-André Chénier
theme: jekyll-theme-cayman  # MathJax-friendly alternative
plugins:
  - jekyll-remote-theme  # Allows GitHub-hosted themes

markdown: kramdown
kramdown:
  math_engine: mathjax